### ISSUE TITLE
log folder write permissions issue

### ISSUE THREAD

**Issue by GeorgelT** [aydancoskun/timetrex-community-edition#1]
Solved the previous issue eventually. I think this one is a lot bigger. 

I managed to get everything installed. Added some users to test everything out. My problem seems to be that no punches get saved to the database. I have made some punches with my test users, but nothing gets listed.

I checked in phpmyadmin, in the punches database there is nothing, but the users are present. Also, even though I have followed the steps and added the timezone, even went as far as manually adding the timezone to mysql, I still get the warning:

WARNING: TimeTrex was unable to set your time zone. Please contact your TimeTrex administrator immediately.

I don't know if this is then related to my punches not being saved.  Is there a log file I can check to see if there are errors at writing to the database?

**Comment by aydancoskun** [comment]
Sorry, this is just a mirror of the timetrex repo because timetrex.com does not keep archive copies. I can't give support for TimeTrex. I am working on FairnessTNA which is a fork of timetrex but its not ready for prime time but you can have a look at the repo
